'use strict';

/* Server specific version of Zone.js */
require('zone.js/dist/zone-node');

const express = require('express');
const ngUniversal = require('@nguniversal/express-engine');

/* The server bundle is loaded here, it's why you don't want a changing hash in it */
const appServer = require('./dist-server/main.bundle');

// *** Setup Express  / Express View ***

const app = express();

/* Configure Angular Express engine */
app.engine('html', ngUniversal.ngExpressEngine({
  bootstrap: appServer.AppServerModuleNgFactory
}));

app.set('view engine', 'html');
app.set('views', 'dist');




/* Server-side rendering */
function angularRouter(req, res) {

  // res.send('Hello World!')

  /* Server-side rendering */
  res.render('index', {
    req,
    res,
    /*providers: [{
      provide: 'serverUrl',
      useValue: `${req.protocol}://${req.get('host')}`
    }]*/
  });


}



// Notes:
// - Root route before static files
//     or it will serve a static index.html without pre-rendering
// - Direct all routes to index.html,
//     where Angular will take care of routing

// Routes:

app.get('/', angularRouter);


// Serve static files
//  generated by the CLI (index.html, CSS? JS, assets...)
app.use(express.static(`${__dirname}/dist`));


// Server
app.listen(3000, () => {
  console.log(`Listening on http://localhost:3000`);
});
