'use strict';

/* Server specific version of Zone.js */
require('zone.js/dist/zone-node');

const express = require('express');
const ngUniversal = require('@nguniversal/express-engine');

/* The server bundle is loaded here, it's why you don't want a changing hash in it */
const appServer = require('./dist-server/main.bundle');

// Activate Google Cloud Trace and Debug when in production
if (process.env.NODE_ENV === 'production') {
  require('@google-cloud/trace-agent').start();
  require('@google-cloud/debug-agent').start();
}

// *** Setup Express  / Express View ***

const app = express();

/* Configure Angular Express engine */
app.engine('html', ngUniversal.ngExpressEngine({
  bootstrap: appServer.AppServerModuleNgFactory
}));

app.set('view engine', 'html');
app.set('views', 'dist');




/* Server-side rendering */
function angularRouter(req, res) {

  // res.send('Hello World!')

  /* Server-side rendering */
  res.render('index', {
    req,
    res,
    /*providers: [{
      provide: 'serverUrl',
      useValue: `${req.protocol}://${req.get('host')}`
    }]*/
  });


}



// Notes:
// - Root route before static files
//     or it will serve a static index.html without pre-rendering
// - Direct all routes to index.html,
//     where Angular will take care of routing

// Routes:

app.get('/', angularRouter);

// Our application will need to respond to health checks when running on
// Compute Engine with Managed Instance Groups.
app.get('/_ah/health', (req, res) => {
  res.status(200).send('ok');
});


// Serve static files
//  generated by the CLI (index.html, CSS? JS, assets...)
app.use(express.static(`${__dirname}/dist`));


// Server
app.listen(3000, () => {
  console.log(`Listening on http://localhost:3000`);
});
